# These are supported funding model platforms

github: # Add your GitHub username here if needed
patreon: # Add your Patreon username if needed
open_collective: # Replace with a single Open Collective username
ko_fi: # Add your Ko-fi username if needed
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL