// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const showcaseGrid: string;
export const card: string;
export const cardLink: string;
export const cardWrapper: string;
export const inner: string;
export const aspect: string;
export const iconBox: string;
export const iconBoxLarge: string;
export const title: string;
export const modalMedia: string;
