// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const timelineSection: string;
export const timelineTitleContainer: string;
export const timelineTitleInner: string;
export const timelineTitleText: string;
export const timelineUnderline: string;
export const shimmer: string;
export const timelineDescriptionText: string;
