// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const timelineSection: string;
export const timelineItem: string;
export const timelineItemTitle: string;
export const timelineItemDescription: string;
