// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const page: string;
export const back: string;
export const meta: string;
export const title: string;
export const lead: string;
export const externalLink: string;
export const content: string;
export const tags: string;
export const tag: string;
