// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const navigationGroup: string;
export const navLinksGroup: string;
export const navButton: string;
export const navButtonActive: string;
