// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const navItem: string;
export const navButton: string;
export const navText: string;
export const navUnderline: string;
export const navItemCompact: string;
export const navGlow: string;
export const glitchEffect: string;
export const navBox: string;
export const navigationGroup: string;
export const navLinksGroup: string;
