// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const footer: string;
export const footerContent: string;
export const footerLinks: string;
export const footerLink: string;
export const footerText: string;
export const mobileNav: string;
export const navItem: string;
export const navIcon: string;
export const navText: string;
export const navItemHighlighted: string;
export const navIconHighlighted: string;
export const navTextHighlighted: string;
