// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const footer: string;
export const footerInner: string;
export const topRow: string;
export const brandBlock: string;
export const brand: string;
export const meta: string;
export const linkColumns: string;
export const linkGroup: string;
export const linkTitle: string;
export const link: string;
export const divider: string;
export const heroBlock: string;
export const heroOutline: string;
export const heroTitle: string;
export const email: string;
export const bottomRow: string;
