// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const header: string;
export const appShellHeader: string;
export const box: string;
export const gradient: string;
export const topBorder: string;
export const bottomBorder: string;
export const highlight: string;
export const scanline: string;
export const scanlineEffect: string;
export const container: string;
