// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const appShellHeader: string;
export const scrolled: string;
export const wordmark: string;
export const container: string;
export const headerGroup: string;
