// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const socialLinkIcon: string;
export const link: string;
export const icon: string;
export const name: string;
