// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const backgroundContainer: string;
export const glowPulse: string;
export const matrixGlow: string;
export const matrixGlowPulse: string;
export const scanline: string;
export const scanlineAnimation: string;
export const matrixOverlay: string;
