// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const pageContainer: string;
export const errorMessage: string;
export const homeLink: string;
export const center: string;
export const stack: string;
export const title: string;
export const text: string;
export const box: string;
export const button: string;
