// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const page: string;
export const back: string;
export const eyebrow: string;
export const title: string;
export const lead: string;
export const list: string;
export const item: string;
export const itemFeatured: string;
export const itemTitle: string;
export const itemExcerpt: string;
export const latestBadge: string;
export const itemArrow: string;
export const chips: string;
export const chip: string;
export const itemMeta: string;
export const itemCover: string;
