// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const contactContainer: string;
export const contactForm: string;
export const stack: string;
export const stackInner: string;
export const title: string;
export const text: string;
export const formStack: string;
