// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const topGradientCircle: string;
export const glowPulse: string;
export const middleRightBlob: string;
export const bottomLeftBlob: string;
export const animatedGridPattern: string;
export const gradientAnimation: string;
export const animatedGradientLinesTop: string;
export const animatedGradientLinesBottom: string;
export const parallaxDivider: string;
export const parallaxDividerInner: string;
export const scrollProgressIndicator: string;
