// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const page: string;
export const back: string;
export const eyebrow: string;
export const title: string;
export const lead: string;
export const list: string;
export const item: string;
export const itemCategory: string;
export const itemTitle: string;
export const itemDescription: string;
export const itemCta: string;
export const empty: string;
export const emptyText: string;
export const emptyCta: string;
