// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const grid: string;
export const card: string;
export const label: string;
export const title: string;
export const hook: string;
export const cta: string;
